import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

///https://medium.com/@onejohi/building-a-simple-rest-api-with-nodejs-and-express-da6273ed7ca9
/// https://redux-toolkit.js.org/tutorials/overview

const X_API_KEY = 'ZTHRTN34346TR456j&%MN&Z56&M%6&634634634';

export interface NumbersObject {
    id: number;
}


export const apiSlice = createApi({
    reducerPath: 'api',
    baseQuery: fetchBaseQuery({
        // Base API controller
        baseUrl: 'http://localhost:3001/',
        prepareHeaders(headers) {
            headers.set('x-api-key', X_API_KEY);

            return headers;
        }
    }),
    endpoints(builder) {
        return {
            // Action
            fetchNumbers: builder.query<NumbersObject[], number | void>({
                query(limit = 10) {
                    return `/?limit=${limit}`;
                }
            })
        }
    }
});
// this hooks are automatically generated by QTK 
export const { useFetchNumbersQuery } = apiSlice;