import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import Person from 'core/entities/Person';
import configuration from '../../config';
///https://medium.com/@onejohi/building-a-simple-rest-api-with-nodejs-and-express-da6273ed7ca9
/// https://redux-toolkit.js.org/tutorials/overview

const X_API_KEY = 'ZTHRTN34346TR456j&%MN&Z56&M%6&634634634';

export interface NumbersObject {
    id: number;
}

export interface Result {
    person: Person[];
}

export const personSlice = createApi({
    reducerPath: 'api',
    baseQuery: fetchBaseQuery({
        // Base API controller
        baseUrl: configuration.dev.AFLI_API_PERSON,
        prepareHeaders(headers) {
            //  headers.set('x-api-key', X_API_KEY);
            return headers;
        }
    }),
    endpoints(builder) {
        return {
            // Action
            getAll: builder.query<Result, void>({
                query() {
                    return `/`;
                }
            })
        }
    }
});
// this hooks are automatically generated by QTK 
export const { useGetAllQuery } = personSlice;